pipeline {
	options {
		timeout(time:30, unit:'MINUTES')
	}
	agent {
		node {
			label 'master'
		}
	}
	stages {
		stage ('BUILD') {
			steps {
				sh 'echo Building...'
			}
		}
		
		stage ("TEST") {
			steps {
				sh ''' echo Testin
				cat /etc/passwd
				'''
				
			}
		}
		stage ("DEPLOY") {
			timeout(time:30, unit:'MINUTES'){
				input message: "Move to next" 	
			}
		}
	}
}
