pipeline {
	options {
		timeout(time:30, unit:'MINUTES')
	}
	environment {
		NAME = "dkr"	
	}
	agent {
		node {
			label 'nodejs'
		}
	}
	stages {
		stage ('BUILD') {
			steps {
				sh 'echo Building: $NAME'
			}
		}
		
		stage ("TEST") {
			steps {
				sh ''' echo Testin
				cat /etc/passwd
				'''
				
			}
		}
		stage ("DEPLOY") {
			steps {
				timeout(time:30, unit:'MINUTES'){
					input message: "Move to next" 	
				}	
			}
		}
	}
}
