pipeline {
  options {
    timeout( time:30, unit:'MINUTES') 
  }
  environment {
   NAME = "ABHIJIT" 
  }
  agent {
    node {
      label 'maven' 
    }
  }
  
  stages {
    stage("BUILD") {
      steps {
        sh '''
          echo "Compiling"
          mvn -s settings.xml clean compile
          
          echo "Packaging"
          mvn -s settings.xml clean package
        '''
      }
    }
  }
}
