pipeline {
  options {
    timeout( time:30, unit:'MINUTES') 
  }
  environment {
   NAME = "ABHIJIT" 
    APPNAME = "movies"
    STAGE = "stage"
    NEXUS_SERVER = "http://nexus-common.apps.na45.prod.nextcle.com/repository/java"
  }
  agent {
    node {
      label 'maven' 
    }
  }
  
  stages {
    stage("BUILD") {
      steps {
        sh '''
          cd pipeline
          echo "Compiling on $NEXUS_SERVER"
          grep url settings.xml
          # mvn -s settings.xml clean compile
          echo "Packaging"
          mvn -s settings.xml clean package
          ls -lrt target
          echo "Building" 
          
          oc delete all -l app=${APPNAME} -n $STAGE
          oc delete all -l build=${APPNAME} -n $STAGE
          
          oc new-build --name=${APPNAME} --binary=true -n $STAGE
        '''
        
        script {
            openshift.withCluster() {
                openshift.withProject("$STAGE") {
                  openshift.selector("bc", "$APPNAME").startBuild("--from-file=${APPNAME}/target/movies.jar","--follow=true", "--wait=true")
            }
          }
        }
      }
    }
  }
}
