pipeline {
  options {
   timeout(time: 10, unit: 'MINUTES')
  }
  agent {
    node {
     label 'master' 
    }
  }
  
  environment {
   PRO = "jentry2"
  }
  
  stages {
    stage('Build') {
      steps {
       echo "** Building" 
      }
    }
    
    stage('Test') {
      steps {
       echo "** Testing" 
      }
    }
    
    stage('Deploy') {
      steps {
       echo "** Deploying" 
      }
    }
  }
}
