pipeline {
  options {
   timeout(time: 10, unit: 'MINUTES')
  }
  agent {
    node {
     label 'maven' 
    }
  }
  
  environment {
   PRO = "jentry2"
   APP = "myjen"
  }
  
  stages {
    stage('Build') {
      steps {
       echo "** Building" 
       echo "Project: ${PRO}"
        sh '''
        ls -lrt
        cd jentry
        mvn -s settings.xml clean package
        oc new-app --name ${APP} java:8 --binary=true -n ${PRO}
        '''
      }
    }
    
    stage('Test') {
      steps {
       echo "** Testing" 
      }
    }
    
    stage('Deploy') {
      steps {
       echo "** Deploying" 
      }
    }
  }
}
